import fs from 'fs/promises';
import path from 'path';
import { executeCommand } from '../executor.js';

export const PROJECT_TEMPLATES = {
  'node-api': {
    name: 'Node.js Express REST API',
    files: {
      'package.json': JSON.stringify({
        name: 'generated-node-api',
        version: '1.0.0',
        type: 'module',
        main: 'server.js',
        scripts: { start: 'node server.js' },
        dependencies: { express: '^4.19.2' }
      }, null, 2),
      'server.js': `import express from 'express';
const app = express();
app.use(express.json());

app.get('/health', (req, res) => res.json({ status: 'ok', timestamp: new Date().toISOString() }));
app.get('/api/items', (req, res) => res.json([{ id: 1, name: 'Sample Item' }]));

const port = process.env.PORT || 3000;
const server = app.listen(port, () => {
  console.log('Server running on port ' + port);
});

if (process.env.AGENT_TEST_RUN === '1') {
  setTimeout(() => {
    console.log('[Verification] Server started and healthy. Exiting test.');
    server.close();
    process.exit(0);
  }, 1000);
}
`
    }
  },
  'python-api': {
    name: 'Python HTTP Service',
    files: {
      'requirements.txt': 'fastapi\nuvicorn\n',
      'main.py': `import os, sys
from http.server import HTTPServer, BaseHTTPRequestHandler
import json

class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({'status': 'active', 'runtime': sys.version}).encode('utf-8'))

def run():
    port = int(os.environ.get('PORT', 8080))
    server = HTTPServer(('127.0.0.1', port), HealthHandler)
    print(f'Serving HTTP on port {port}')
    if os.environ.get('AGENT_TEST_RUN') == '1':
        print('[Verification] Python service loaded cleanly. Exiting test.')
        return
    server.serve_forever()

if __name__ == '__main__':
    run()
`
    }
  },
  'static-web': {
    name: 'Modern Web Landing Page',
    files: {
      'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated App</title>
  <style>
    body { font-family: system-ui, sans-serif; margin: 0; padding: 2rem; background: #0f172a; color: #f8fafc; }
    .card { background: #1e293b; padding: 2rem; border-radius: 12px; max-width: 600px; margin: 0 auto; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.3); }
    h1 { color: #38bdf8; margin-top: 0; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Project Generated by Inject Agent</h1>
    <p>Autonomous scaffolding and runtime error detection engine.</p>
  </div>
</body>
</html>`
    }
  }
};

export async function buildProjectFromPrompt({ prompt, targetDir = './generated-app', files = null, autoRun = true }) {
  const workspacePath = path.resolve(process.cwd(), targetDir);
  await fs.mkdir(workspacePath, { recursive: true });

  const generatedFiles = [];
  const errors = [];

  let filesToWrite = {};

  if (files && typeof files === 'object' && Object.keys(files).length > 0) {
    filesToWrite = files;
  } else {
    const lower = prompt.toLowerCase();
    if (lower.includes('python') || lower.includes('flask') || lower.includes('fastapi')) {
      filesToWrite = PROJECT_TEMPLATES['python-api'].files;
    } else if (lower.includes('html') || lower.includes('landing') || lower.includes('site') || lower.includes('css')) {
      filesToWrite = PROJECT_TEMPLATES['static-web'].files;
    } else {
      filesToWrite = PROJECT_TEMPLATES['node-api'].files;
    }
  }

  for (const [relPath, content] of Object.entries(filesToWrite)) {
    const fullPath = path.join(workspacePath, relPath);
    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    await fs.writeFile(fullPath, content, 'utf8');
    generatedFiles.push(relPath);
  }

  let executionResult = null;
  if (autoRun) {
    if (filesToWrite['server.js']) {
      const checkRes = await executeCommand('node --check server.js', workspacePath);
      if (!checkRes.success) {
        errors.push({ stage: 'syntax_check', detail: checkRes.stderr || checkRes.stdout });
      }
      executionResult = checkRes;
    } else if (filesToWrite['main.py']) {
      const checkRes = await executeCommand('python -m py_compile main.py', workspacePath);
      if (!checkRes.success) {
        errors.push({ stage: 'python_compile', detail: checkRes.stderr || checkRes.stdout });
      }
      executionResult = checkRes;
    }
  }

  return {
    success: errors.length === 0,
    workspacePath,
    generatedFiles,
    errors,
    executionResult
  };
}
